### ISSUE TITLE
Age & Date of birth are calculated wrong

### ISSUE THREAD

**Issue by anamariadem** [kislakiruben/parsecnp#15]
Hello, I've been using this library for a few months and I noticed that in some cases the age is calculated as 100 + the correct age, more exactly if the age is smaller than 14 (e.g 6120401018281, expected value is 10, actual value is 110). I have looked into the source code and the problem is in dateParser.js, line 17.

**Comment by kislakiruben** [comment]
@anamariadem could you show me an example date (just `YYMMDD`) for when this is happening to you?

**Comment by kislakiruben** [comment]
@anamariadem this should be fixed now. thanks for finding it and reporting it!
